Lesson4 complete
Yarslv/FirstWeekApp pull request #4
Opened 2022-06-22 23:57 UTC by Yarslv

2022-06-23 09:22 UTC, shadwork requested changes
все хорошо - но не работает в принципе
 - проверь какие именно пермишины нужны

2022-06-23 09:22 UTC, shadwork commented on app/src/main/java/com/internship/firstweekapp/ui/wifi_fragment/WiFisFragment.kt
> +            val radiusOne = min(binding.constraint.width, binding.constraint.height) / 30 / 2
is 30 / 2 equal to 15 ?

2022-06-25 03:10 UTC, Yarslv commented on app/src/main/java/com/internship/firstweekapp/ui/wifi_fragment/WiFisFragment.kt
> +            val radiusOne = min(binding.constraint.width, binding.constraint.height) / 30 / 2
Це я думав що розмах децибел від -30 до 30

2022-06-25 13:17 UTC, shadwork approved these changes

2022-06-25 13:26 UTC, closed without merging