Added first scene
Yarslv/FirstWeekApp pull request #7
Opened 2022-07-07 01:38 UTC by Yarslv

2022-07-07 13:09 UTC, shadwork requested changes
очень хорошо
дописывай

2022-07-07 13:09 UTC, shadwork commented on app/src/main/java/com/internship/firstweekapp/data/Game.kt
> +                actions.add(SimpleText("It's only when I hear the sounds of shuffling feet and supplies being put away that I realize that the lecture's over."))
Good - but text should be in android resources

2022-07-07 13:09 UTC, shadwork commented on app/src/main/java/com/internship/firstweekapp/ui/splash/SplashFragment.kt
>      private fun showLogInScreen() {
rename please

2022-07-07 13:09 UTC, shadwork commented on app/src/main/java/com/internship/firstweekapp/ui/test/CustomTextView.kt
> +                    Color.parseColor("#cc6404"),
move color into android res

2022-07-09 06:38 UTC, Yarslv commented on app/src/main/java/com/internship/firstweekapp/ui/splash/SplashFragment.kt
>      private fun showLogInScreen() {
yes

2022-07-09 06:38 UTC, Yarslv commented on app/src/main/java/com/internship/firstweekapp/ui/test/CustomTextView.kt
> +                    Color.parseColor("#cc6404"),
ok

2022-07-09 06:39 UTC, Yarslv commented on app/src/main/java/com/internship/firstweekapp/data/Game.kt
> +                actions.add(SimpleText("It's only when I hear the sounds of shuffling feet and supplies being put away that I realize that the lecture's over."))
ok

2022-07-09 12:36 UTC, shadwork approved these changes
Норм - особенно после правок

2022-07-09 12:36 UTC, merged